### ISSUE TITLE
cuDNN error

### ISSUE THREAD

**Issue by GiorgioPeng** [alexrame/mixmo-pytorch#2]
Hello, can u tell me your GPU type and CUDA version?
I tried to use **CUDA V11.0.221** + **RTX3090** to train the baseline of the model.
Then I got an error **RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR**.
Actually, I am training the baseline on my CPU and it is working fine but slowly.
I want to use the GPU to help me get higher training speed.
Thanks for reading.

**Comment by alexrame** [comment]
Thank you for your question.
Our experiments ran on a single NVIDIA 12Go-TITAN X Pascal GPU, with CUDA Version: 10.2.
Please reopen this issue if this does not fix your issue.
