### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by jjb202** [alexrame/mixmo-pytorch#4]
Hi, I want to fuse two tensors using Mixing Block, which function do I need to call?

**Comment by alexrame** [comment]
Thank you for your interest.

All tensors merging operations are defined in mixmo/augmentations/mixing_blocks.py.
Then, depending on the merging operation you want to use (summing, patch mixing, etc. See MASK_MIX_DICT for an exhaustive list), you should select the appropriate function.
Most functions are copied from the open-source codes from the papers that first introduced their own methods.

Note that MixMo does not introduce a new mixing block: instead, we show that using already-existing mixing blocks to mix different inputs in features while keeping the labels apart works even better.

I hope this will address your question.
